### PR TITLE
Responsive cat page

### PR DESCRIPTION
**Pull request by ruangroc**
Addressing #2

Does this work on your screens, @thuyvyng ?

image

image

image

### CODE REVIEW

**Review by thuyvyng — APPROVED** [review]
yay its responsive!!

small nit, can u change the name of it from Your Spotify Statistics to like Your Spotify Purrsona / Purrsonality or something like that to reflect new cat names

**Comment by thuyvyng** [comment]
Screen Shot 2023-01-13 at 3 43 01 PM
small nit i dont like how theyre uneven sizes but we can leave it bc i think we are gonna rework the layout of this page right

**Comment by thuyvyng** [comment]
Screen Shot 2023-01-13 at 3 47 27 PM
the buttons dont align even on full screen for me?

**Comment by thuyvyng** [comment]
also side question, do we want to deploy this as it is now responsive and work on updates? or do u wanna hold off or

**Comment by ruangroc** [comment]
yeah let's rework those buttons when we rework the overall page. I don't really like them as is now anyway.
And yeah I'm down to have it be deployed

**Review by thuyvyng — CHANGES_REQUESTED** [review]
actually please fix the alignment of button

**Review by thuyvyng — APPROVED** [review]
yayayyayyay amazing stunning what fab work, hess would be so proud

**Pull request merged**
