### PR TITLE
i added music!

### PR DESCRIPTION
**Pull request by thuyvyng**
added a very basic way of playing music
- click on the play button and it plays
- if you click another play button it will stop the current play and play whatever u pressed
- there is no way to stop the music until the song ends

so ya maybe eventually we wanna do hover for music but honestly sometimes i hate when music plays when i dont expect it, we can discuss. but if we stick with how i did it then we need to implement a way to either stop the music and to visualize which song is playing (aka like turn the play icon into a pause icon u know)

this will also depend on how we implement this page so im holding off on more work

### CODE REVIEW

**Comment by ruangroc** [comment]
omg I love the music, but yes, not being able to pause it is kinda weird. 
honestly I'd love to keep the top 10 songs and artists part of this page since it changes when the data timeframe changes too and it's fun to see. 
maybe we can make the top 10 lists look more natural on the page though? or tie it in somehow with the cat visualization?

**Comment by thuyvyng** [comment]
> ongs an

do u want me to add a way to pause it? bc i kind of think we should implement that depencing on how we change the cat page, i kinda think we should add like the song image and have it like semi greyed out if it not playing and then if u click it then its full opacity instead of the triangle play button

and what do u think about hover/onclick

**Comment by ruangroc** [comment]
oooh I like the semi-greyed out idea. I also don't like when things play when I simply hover, I'd rather manually click to start and stop the music

**Comment by thuyvyng** [comment]
ok if we want a way to pause the music i think im gonna close out this pr until we decide the layout and design of this page, that cool w u? or do u want it before we deploy it?

**Comment by ruangroc** [comment]
that's fine, that makes sense

**Comment by thuyvyng** [comment]
update i lied, i did it anyways bc i want music

**Comment by ruangroc** [comment]
Nit: the pictures are tiny when I shrink my screen but that can be a future iteration
image

**Review by ruangroc — APPROVED** [review]

**Comment by thuyvyng** [comment]
i made it bigger than what it was originally set as but given that we are likely changing the layout i didnt want to put the work in

**Pull request merged**
